### ISSUE TITLE
Handling of "Weird" MC answers doesn't look right

### ISSUE THREAD

**Issue by RPrimrose** [HotDocsCorp/hotdocs-open-sdk#23]
https://github.com/HotDocsCorp/hotdocs-open-sdk/commit/384f9eeb52f403bcb86feb133a06fc40dfc58eff doesn't look quite right to me

Shouldn't selValueUnans be set to false within the while loop? Otherwise if we have this
```
<Answer name=""Some MC Value"">
  <MCValue>
    <SelValue unans=""true""></SelValue>
    <SelValue>Test</SelValue>
  </MCValue>
</Answer>
```

Then when it gets to the second SelValue it will still have selValueUnans as true and will skip over it.

**Comment by lowellstewart** [comment]
I've checked in a significant improvement to the way we read Answer XML. This (and many issues like it) should be addressed now.  In this case, I changed the answer reading so it ignores any SelValues that are set to unanswered, but pays attention to those that are not.  Also greatly improved our support for empty XML elements like <SelValue/>.
