### ISSUE TITLE
Overlaying answer XML does not work properly when some answers are empty

### ISSUE THREAD

**Issue by RPrimrose** [HotDocsCorp/hotdocs-open-sdk#24]
The following test will currently fail, saying that AnswerCount is only 4. 
```
var anscol = new AnswerCollection();
const string answerXML =
	"<?xml version=\"1.0\" standalone=\"yes\"?><AnswerSet title=\"\" version=\"1.1\" useMangledNames=\"false\">" +
	"<Answer name=\"Foreign Parties tx\"><TextValue></TextValue></Answer>" +
	"<Answer name=\"Property Address Line tx\"><TextValue>[     ] </TextValue></Answer>" +
	"<Answer name=\"Property Address Block tx\" save=\"false\"><TextValue></TextValue></Answer>" +
	"<Answer name=\"HDCtrlDocName\"><TextValue>asd</TextValue></Answer>" +
	"<Answer name=\"Group tx\"><TextValue unans=\"true\" /></Answer>" +
	"<Answer name=\"Fee Earner tx\"><TextValue unans=\"true\" /></Answer></AnswerSet>";
var sr = new StringReader(answerXML);
anscol.OverlayXml(sr);
Assert.AreEqual(6, anscol.AnswerCount);
```

I played around in the debugger and it looks like the problem is because empty elements don't have a corresponding EndElement and the ReadValue method doesn't account for this properly.

Specifically: we're processing the first answer in OverlayXml() and we enter the ReadValue method. In there we get into the else statement in this block
```
if (ans == null)
	ans = CreateAnswer<TextValue>(answerName);
if (unans)
	ans.InitValue<TextValue>(userModifiable ? TextValue.Unanswered : TextValue.UnansweredLocked, repeatStack);
else
{
	reader.ReadStartElement("TextValue");
	ans.InitValue<TextValue>(new TextValue(reader.Value, userModifiable), repeatStack);
	reader.Read(); // move past text element
}
reader.Read(); // read past TextValue element
reader.MoveToContent();
break;
```

After we perform ReadStartElement the reader is sitting at the start element for the TextValue.
We then do a read, which gets us to the EndElement of the answer element. 
We then do a second read, which gets us to the next answer node ("Property Address Line tx"). 
We then come out of this code and eventually end up at the start of the while loop, which performs another read and means we miss the "Property Address Line tx" answer.

**Comment by lowellstewart** [comment]
I've checked in a significant improvement to the way we read XML.  This (and many issues like it) should be addressed now.
