### ISSUE TITLE
Properties in the InterviewSettings class are held in a dictionary instead of being backed by individual fields?

### ISSUE THREAD

**Issue by RPrimrose** [HotDocsCorp/hotdocs-open-sdk#29]
We're having a problem serializing/deserializing an InterviewSettings object from JSON. I’ll explain our problem below but there’s a general aspect of the InterviewSettings class that we’re unclear on and could do with guidance about. Most of the class's properties are stored in the “_settings” dictionary instead of just being backed by fields as would be usual. E.G. The definition for InterviewRuntimeUrl is:

```
public string InterviewRuntimeUrl
{
    get
    {
        return GetSettingString("HotDocsJsUrl");
    }
    set // private?
    {
        SetSettingString("HotDocsJsUrl", value);
    }
}
```

I’m not sure why we’re using this dictionary?

The reason I ask is that when deserializing the constructor sets properties that indirectly add keys to the _settings dictionary and then the deserializer tries to directly add the serialized keys to the _settings dictionary causing an exception due to adding a duplicate key. E.G. it sets InterviewRuntimeUrl which creates a “HotDocsJsUrl” key and then it tries to directly add the serialized “HotDocsJsUrl” key. 

We can work around this by not passing around a serialized InterviewSettings object but instead our own representation of it which we then manually construct an InterviewSettings object from, but I’m curious if we could just change the InterviewSettings class to not use a dictionary instead or possible to mark the _settings dictionary as non-serializable?

The serialized JSON looks like

```
"{\"InterviewAnswers\":null,\"SettingsForInterview\":{\"PostInterviewUrl\":\"postinterviewUrl\",\"InterviewRuntimeUrl\":\"https://hdcore.blob.core.windows.net/serverfiles/%version%/js\",\"InterviewFileUrl\":\"interviewFileUrl\",\"StyleSheetUrl\":\"https://hdcore.blob.core.windows.net/serverfiles/%version%/stylesheets\",\"DocumentPreviewUrl\":null,\"SaveAnswersUrl\":null,\"AnswerFileDataServiceUrl\":null,\"CustomDataSources\":null,\"AddHdMainDiv\":1,\"RoundTripUnusedAnswers\":true,\"MarkedVariables\":null,\"Settings\":{\"HotDocsCssUrl\":\"https://hdcore.blob.core.windows.net/serverfiles/%version%/stylesheets/hdsuser.css\",\"AddHdMainDiv\":\"true\",\"FormActionUrl\":\"postinterviewUrl\",\"HotDocsJsUrl\":\"https://hdcore.blob.core.windows.net/serverfiles/%version%/js\"},\"Format\":2,\"ThemeName\":\"hdsuser\",\"Title\":null,\"Locale\":null,\"NextFollowsOutline\":0,\"ShowAllResourceButtons\":0,\"DisableDocumentPreview\":false,\"DisableSaveAnswers\":false,\"DisableAnswerSummary\":0,\"AnswerSummary\":{\"Format\":0,\"Border\":0,\"PercentWidthForPrompt\":0,\"IndentPrompts\":0,\"BulletPrompts\":0,\"IndentAnswers\":0,\"BulletAnswers\":0},\"DefaultUnansweredFormat\":0,\"HonorCmpUnansweredFormat\":0,\"DefaultDateFormat\":null},\"InterviewMarkedVariables\":null,\"LogRef\":\"OnPremiseLoggingReference\"}"
```

**Comment by lowellstewart** [comment]
I originally decided to store the settings in a dictionary as a means of simplifying cross-version compatibility and (ironically) serialization, although I admit we never had the chance to finish or test much regarding the behavior of these classes when serializing.  Which would explain the issues you're seeing.  I was also trying to share serialization and cross-version compatibility in the Settings base class, such that it could easily be reused for both InterviewSettings and AsssembleDocumentSettings.

Basically, the idea was that the settings ought to serialize in exactly the same way a dictionary serializes. That way, any version of the settings class could theoretically deserialize settings that had been serialized by a different version of the settings class.  As things evolve, there will undoubtedly be new settings introduced, and there might potentially be old settings we deprecate. But the hope was that, as long as core "required" settings are still present, other settings could come and go, and serialized settings (perhaps stored as preferences in a host application) could be re-used across SDK version upgrades (and potentially HotDocs version upgrades).

If we stick to this way of working, then individual property values shouldn't really be serialized -- just the dictionary.  But if you think the same cross-version compatibility could be achieved by serializing the properties only, without using the dictionary, then that might be more straight-forward.

I'm afraid my early thinking about how these classes might be serialized/de-serialized in practice was only that -- early thinking.  I was not able to push the implementation along to the point where such serialization was actually used in practice.  So it's good to get this figured out now -- better late than never.

**Comment by stevenswan** [comment]
Hi Lowell

When trying to serialize the interviewsettings object we noticed that some of the properties are not strings and are booleans or IEnumerable so all of the settings cannot be put into the dictionary. We are trying to think of a way to serialize the object for cross-version compatibility but finding it a bit difficult.

**Comment by stevenswan** [comment]
I figured out that I was using InterviewSettings in the wrong way entirely trying to serialize the object instead of adding the values in the settings dictionary to the query string, sorry about that!

**Comment by lowellstewart** [comment]
No problem Steven, glad you worked it out. I think we're all looking forward to improved documentation, as that's going to help a great deal. :-)
